### ISSUE TITLE
about the extra_hosts

### ISSUE THREAD

**Issue by danaoairuike** [berserkbuddhist/minio#1]
Hi, 

extra_hosts:
      - "minio1:10.10.10.1"  # 1st node
      - "minio2:10.10.10.2"  # 2nd node
      - "minio3:10.10.10.3"  # 3rd node

For this extra_hosts, the ip `10.10.10.x` is just a sample ? we should use the real ipv4 address of each server ? Thanks

**Comment by berserkbuddhist** [comment]
Yes, those are just samples!
Use your own IP addresses.
